#!/usr/bin/env bash

BASE_DIR=${1:-${HOME}}
APT_CACHE_DIR="$HOME/apt/cache"
APT_STATE_DIR="$HOME/apt/state"
APT_OPTIONS="-o debug::nolocking=true -o dir::cache=$APT_CACHE_DIR -o dir::state=$APT_STATE_DIR"
mkdir -p "$APT_CACHE_DIR/archives/partial"
mkdir -p "$APT_STATE_DIR/lists/partial"

apt-get $APT_OPTIONS update
